ratings:
  namespace: student39-bookinfo-prd
  image: ghcr.io/zyict/bookinfo-ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.opsta.net
  path: "/student39/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/ratings
  COMMIT_SHA: CHANGEME
